### PR TITLE
Export HTML from evernote instead of text.

### PR DESCRIPTION
**Pull request by zhougy0717**
Hi,
Exporting only text will lose most of the data if you are going to import post from your Evernote note. I leverage one of your other projects (enml2html) to do this work. It works well with my hexo server.

The functionalities include:
1.Export HTML of a note from Evernote. Download all image resource from that note and show them in img tag of that html. 
2.Add mocha test cases.

### CODE REVIEW

**Comment by nswbmw** [comment]
IMO:

1. i remember yinxiang not support open-link，so export HTML is not work well.
2. personal use evernote as markdown notebook..

You may create another repo, like `everblog-adaptor-hexo-html`, for your taste.

**Comment by zhougy0717** [comment]
You are right. So I export all images to local drive and put the path into
SRC field.
As you suggested, I will post it in another repo.
What I'm curious about is how you utilize your evermore. Evernote doesn't
have good markdown support. It must be tricky to write note directly in
evernote with markdown syntax.

Anyway,thanks for your suggestion.

2017年6月29日 上午10:04，"nswbmw" <notifications@github.com>写道：

**Comment by nswbmw** [comment]
I wrote plain text rather than markdown...not much pictures.

**Comment by zhougy0717** [comment]
Hi,
I just realized recently that you have re-arched the everblog project. But
it seems you reverted the patch I provided last year for increasing build.
So I got a lot of rate limit exception while exporting notes from Evernote.
And you also re-design the interface for the adapters, which makes my
everblog-adapter-hexo-html not work.
What's your plan on this project? Will you commit to keep it open to
community? The change makes me not able to use. And it's not so friendly to
the 3rd party adapters.

**Pull request closed without merging**
